service: default
runtime: python
runtime_config:
  python_version: 3

env: flex

manual_scaling:
    instances: 1

resources:
    cpu: 1
    memory_gb: 3.0
    disk_size_gb: 10
    
entrypoint: gunicorn --preload -b 0.0.0.0:8080 main:server --timeout 120



inbound_services:
- warmup